name: Beta Release Workflow

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:
  beta-release:
    if: github.event.issue.pull_request && contains(github.event.comment.body, 'beta-release-bot')
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Set referenced package
        run: |
          REFERENCED_PACKAGE=$(echo "${{ github.event.comment.body }}" | sed -n 's/.*beta-release-bot (\([^)]*\)).*/\1/p')
          echo "Referenced package: $REFERENCED_PACKAGE"
          echo "REFERENCED_PACKAGE=$REFERENCED_PACKAGE" >> $GITHUB_ENV

      - name: Confirm referenced package exists
        run: |
          if [ ! -d "./projects/$REFERENCED_PACKAGE" ]; then
            echo "Error: Directory ./projects/$REFERENCED_PACKAGE does not exist."
            exit 1
          fi

      - name: Update package.json with beta
        run: |
          BETA_APPEND_STRING=$(echo "${{ github.event.comment.body }}" | sed -n "s/.*beta-release-bot ($REFERENCED_PACKAGE): \(.*\)/\1/p" | tr -d ' ')
          PACKAGE_VERSION=$(node -p "require('./projects/$REFERENCED_PACKAGE/package.json').version")
          echo "Current version: $PACKAGE_VERSION"
          NEW_VERSION="$PACKAGE_VERSION-$BETA_APPEND_STRING"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New version: $NEW_VERSION"
          jq --arg newVersion "$NEW_VERSION" '.version = $newVersion' ./projects/$REFERENCED_PACKAGE/package.json > ./projects/$REFERENCED_PACKAGE/package.json.tmp
          mv ./projects/$REFERENCED_PACKAGE/package.json.tmp ./projects/$REFERENCED_PACKAGE/package.json

      - name: Install Dependencies
        run: npm ci

      - name: Build Library
        run: npm run build:$REFERENCED_PACKAGE

      - name: Authenticate to codeartifact
        run: aws codeartifact login --tool npm --repository shared-package-repository --domain shared-package-domain --namespace @hsi

      - name: Deploy to codeartifact
        run: |
          cd ./dist/$REFERENCED_PACKAGE
          npm publish

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const workflow = '${{ github.workflow  }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const pkg = '${{ env.REFERENCED_PACKAGE }}';
            const version = '${{ env.NEW_VERSION }}';
            let body = `[${workflow} (${pkg})](${url}): ${success ? 'succeeded ✅' : 'failed ❌'}`;
            if (success) {
              body = body + `\n\nTo install, run \`npm install @hsi/${pkg}@${version}\``;
            }

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
