name: Beta Release Workflow

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  pull-requests: write
  contents: write
  issues: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json

jobs:
  beta-release:
    # if: github.event.issue.pull_request && contains(github.event.comment.body, 'beta-release-bot:')
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # - name: Get PR branch
      #   uses: xt0rted/pull-request-comment-branch@v2
      #   id: comment-branch

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Set referenced package
        run: |
          REFERENCED_PACKAGE=viz-components
          echo "Referenced package: $REFERENCED_PACKAGE"
          echo "REFERENCED_PACKAGE=$REFERENCED_PACKAGE" >> $GITHUB_ENV

      - name: Confirm referenced package exists
        run: |
          if [ ! -d "./libs/$REFERENCED_PACKAGE" ]; then
            echo "Error: Directory ./libs/$REFERENCED_PACKAGE does not exist."
            exit 1
          fi

      - name: Install Dependencies
        run: npm ci

      - name: Authenticate to codeartifact
        run: aws codeartifact login --tool npm --repository shared-package-repository --domain shared-package-domain --namespace @hsi

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Get current beta version
        id: beta_version
        env:
          REFERENCED_PACKAGE: ${{ env.REFERENCED_PACKAGE }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/get_beta_version.sh

      - name: Beta release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_REGION: us-east-1
        run: |
          npx nx build $REFERENCED_PACKAGE
          cd dist/$REFERENCED_PACKAGE
          npm version $beta_version --no-git-tag-version
          npm publish

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const workflow = '${{ github.workflow  }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = '${{ job.status }}' === 'success';
            const pkg = process.env.REFERENCED_PACKAGE;
            const version = process.env.beta_version;
            let body = `[${workflow} (${pkg})](${url}): ${success ? 'Succeeded ✅' : 'Failed ❌'}`;
            if (success) {
              body = body + `\n\nTo install, run \`npm install @hsi/${pkg}@${version}\``;
            }
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
